### ISSUE TITLE
CSV formatting

### ISSUE THREAD

**Issue by endolith** [peterhurford/ea-data#7]
CSV doesn't seem to be formatted correctly.  First lines are:

```
id,referrer_url,heard_ea,is_ea,is_ea_comment, ... ,income_2016_household_c,income_2016_individual_c
	 ,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA, ... ,NA,NA,NA,NA,NA,NA
"	 ""","EAs_sometimes_think_some_causes_are_more_important_than_others._

	If_you_can,_please_give_a_rough_ ... _EAs._[Global_Poverty]","EAs_sometimes_think_ ... others._

	If_you_can,_please_give_a_rough_ ... _EAs._[Improving_rationality_or_science]","EAs_sometimes_think_ ... others._
```

- What are all the NAs for
- Why are they on a newline 
- and then `"	 """`?
- I get that the "EAs_sometimes_think ..." are multi-line cells because of the quotation marks, but even multi-line headers are a bit weird.

**Comment by peterhurford** [comment]
None of the headers are multi-line.

It looks like the first two lines of the CSV are garbled, though. I removed them in https://github.com/peterhurford/ea-data/pull/10.

NAs mean that the particular respondent (represented by the row) did not provide a response for that particular variable (represented by the column).

**Comment by peterhurford** [comment]
I'm going to close this now, but feel free to reopen if you still have questions.
